apiVersion: v1
kind: Service     # Creating a Service for Redis
metadata:
  name: redis
  labels:
    name: redis
    app: demo
spec:
  ports:          # Defining Port Definition
  - port: 6379    # Default option is to expose as a cluster ip
    name: redis
    targetPort: 6379
  selector:       # This will ensure that appropiate port is receiving the traffic
    name: redis   # matches the labels in the pod
    app: demo
